name: EPG Update
# env:
#  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
permissions:
  contents: write

concurrency:
  group: epg-update
  cancel-in-progress: false

on:
  schedule:
    - cron: '0 19 * * *'        # UTC时间：19点，北京时间：次日凌晨3点
    - cron: '0 07 * * *'        # UTC时间：7点，北京时间：当天下午15点
  workflow_dispatch:
 
jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'

                   
    #   - name: Display Chrome path (debug)
    #     run: |
    #       which chrome
    #       which chromedriver
    #       chrome --version
          

      - name: Install Python dependencies
        run: |
          pip install selenium lxml webdriver-manager

      - name: Run EPG scraper
        run: python rudong-epg.py   # 这里指定需要执行的脚本文件名

      - name: Compress epg.xml (optional)
        run: gzip -c epg.xml > epg.xml.gz || true

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add epg.xml epg.xml.gz 2>/dev/null || true
          git commit -m "Update EPG data (skip ci)" || echo "No changes to commit"
          git push
          
          
  sync-to-gitee:
    runs-on: ubuntu-latest
    needs: update-epg          # 只有主任务成功后才运行

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH key for Gitee
        env:
          GITEE_SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GITEE_SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H gitee.com >> ~/.ssh/known_hosts

      - name: Push ONLY epg.xml and epg.xml.gz to Gitee
        run: |
          git remote add gitee git@gitee.com:magihub/epg.git
          git checkout --orphan temp_epg_only
          git rm -rf .
          git add epg.xml epg.xml.gz
          git commit -m "Update EPG data only"
          git push gitee temp_epg_only:main --force
          git checkout main
          git branch -D temp_epg_only